version: '3'
services:
  analyzer-dispatcher:
    image: analyzer-dispatcher.build:latest
    build:
      context: ./
      dockerfile: ./analyzer-dispatcher/Dockerfile

  generic-subgraph-generator:
    image: generic-subgraph-generator:latest
    build:
      context: ./
      dockerfile: ./generic-subgraph-generator/Dockerfile
